import { open } from "@tauri-apps/plugin-dialog";
import { useEffect, useRef, useState } from "react";
import { vaultConnect, vaultDisconnect, vaultDocuments, vaultRebind, vaultRebindProject, vaultRecoverOperations, vaultStatus, vaultRegisterProject, type VaultStatus, type Vault, type VaultDocument } from "../../lib/knowledge-vault-ipc";
import { LOCAL_HOST, type HostId } from "../../lib/transport";
import { vaultButton, vaultCard, vaultError, vaultLabel } from "./ui";

export function VaultSettings({ repo, host, onChanged }: { repo?: string; host: HostId; onChanged?: () => Promise<void> }) {
  const [vault, setVault] = useState<Vault | null>(null); const [chosen, setChosen] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [confirm, setConfirm] = useState(false); const [busy, setBusy] = useState(false); const [supported, setSupported] = useState(true); const [status, setStatus] = useState<VaultStatus | null>(null); const [rebind, setRebind] = useState<Vault | null>(null); const [rebindPath, setRebindPath] = useState(""); const [rebindDocs, setRebindDocs] = useState<VaultDocument[]>([]); const [rebindQuery, setRebindQuery] = useState(""); const [rebindPage, setRebindPage] = useState(0); const [confirmed, setConfirmed] = useState<string[]>([]); const [recovery, setRecovery] = useState(""); const [projectPath, setProjectPath] = useState("");
  const loadRequest = useRef(0); const rebindRequest = useRef(0); const pickerRequest = useRef(0);
  const load = async () => { const request = ++loadRequest.current; if (host !== LOCAL_HOST) { setLoading(false); return; } setLoading(true); try { const status = await vaultStatus(host, repo); if (request !== loadRequest.current) return; setStatus(status); setSupported(status.supported !== false); setVault(status.vaults.find(item => item.enabled) ?? null); } catch (reason) { if (request === loadRequest.current) setError(String(reason)); } finally { if (request === loadRequest.current) setLoading(false); } };
  useEffect(() => { rebindRequest.current++; pickerRequest.current++; setProjectPath(""); setRebind(null); setRebindPath(""); setConfirmed([]); void load(); }, [host, repo]);
  if (host !== LOCAL_HOST) return <section className={vaultCard}><h2 className="font-medium">자료함 연결</h2><p className="mt-2 text-sm text-text-secondary">개인 지식창고는 로컬 세션에서만 사용할 수 있습니다.</p></section>;
  if (!supported) return <section className={vaultCard}><h2 className="font-medium">자료함 연결</h2><p className="mt-2 text-sm text-text-secondary">개인 지식창고는 현재 macOS Desktop에서 지원합니다.</p></section>;
  const changed = async () => { await load(); await onChanged?.(); };
  const mutate = async (work: () => Promise<unknown>) => {
    if (busy) return;
    setBusy(true); setError("");
    try { await work(); setChosen(""); setConfirm(false); await changed(); }
    catch (reason) { setError(String(reason)); }
    finally { setBusy(false); }
  };
  const beginRebind = async (target: Vault) => {
    const request = ++rebindRequest.current;
    setError(""); setRebind(target); setRebindPath(""); setRebindQuery(""); setRebindPage(0); setConfirmed([]);
    try { const documents = await vaultDocuments(target.id, host); if (request === rebindRequest.current) setRebindDocs(documents); }
    catch (reason) { if (request === rebindRequest.current) setError(String(reason)); }
  };
  const pickRebindPath = async () => { const request = ++pickerRequest.current; try { const path = await open({ directory: true, multiple: false }); if (request === pickerRequest.current && typeof path === "string") setRebindPath(path); } catch (reason) { if (request === pickerRequest.current) setError(String(reason)); } };
  const candidates = rebindDocs.filter(item => item.title.toLocaleLowerCase().includes(rebindQuery.toLocaleLowerCase()));
  const visibleCandidates = candidates.slice(rebindPage * 100, (rebindPage + 1) * 100);
  const confirmableIds = candidates.flatMap(item => item.current_revision_id ? [item.current_revision_id] : []);
  const projectBinding = status?.project_binding ?? status?.prior_bindings.find(item => item.active) ?? null;
  return <section className={`${vaultCard} space-y-3`}><h2 className="font-medium">자료함 연결</h2>{loading ? <p className="text-sm text-text-secondary">불러오는 중…</p> : vault ? <><p className="break-all text-sm text-text-secondary">{vault.vault_root}</p>{confirm ? <div className="space-y-2"><p className="text-sm text-text-secondary">파일은 유지됩니다. 연결을 해제할까요?</p><div className="flex gap-2"><button className={vaultButton} disabled={busy} onClick={() => void mutate(() => vaultDisconnect(vault.id, host))}>해제 확인</button><button className={vaultButton} disabled={busy} onClick={() => setConfirm(false)}>취소</button></div></div> : <button className={vaultButton} disabled={busy} onClick={() => setConfirm(true)}>해제</button>}</> : <><button className={vaultButton} disabled={busy} onClick={() => void open({ directory: true, multiple: false }).then(path => { if (typeof path === "string") setChosen(path); }).catch(reason => setError(String(reason)))}>디렉터리 선택</button>{chosen && <div className="space-y-2"><p className="break-all text-sm text-text-secondary">{chosen}</p><button className={vaultButton} disabled={busy} onClick={() => void mutate(() => vaultConnect(chosen, host))}>연결</button></div>}</>}{error && <p role="alert" className={vaultError}>{error}</p>}{repo && <p className="break-all text-xs text-text-secondary">{repo}</p>}
    {vault && repo && status && <div className="mt-4 space-y-3 border-t border-border pt-3">
      <h3 className="font-medium">프로젝트 등록</h3>
      {!status.project_binding ? <button className={vaultButton} disabled={busy} onClick={() => void mutate(() => vaultRegisterProject(repo, host))}>현재 프로젝트 등록</button> : <p className="text-sm text-text-secondary">이 프로젝트는 창고에 등록돼 있습니다. 아래에서 위치를 바꿀 수 있습니다.</p>}
    </div>}
    {vault && <section className="space-y-2 border-t border-border pt-3"><h3 className="font-medium">자료함 위치 변경</h3><button className={vaultButton} disabled={busy} onClick={() => void beginRebind(vault)} type="button">새 위치로 연결</button></section>}
    {!vault && status?.vaults.filter(item => !item.enabled).map(item => <button className={vaultButton} disabled={busy} key={item.id} onClick={() => void beginRebind(item)} type="button">기존 자료함 다시 연결: {item.vault_root}</button>)}
    {rebind && <section className="space-y-2 rounded-md border border-border bg-bg p-3"><p className="break-all text-sm text-text-secondary">기존 위치: {rebind.vault_root}</p><button className={vaultButton} disabled={busy} onClick={() => void pickRebindPath()} type="button">새 디렉터리 선택</button>{rebindPath && <p className="break-all text-sm text-text-secondary">새 위치: {rebindPath}</p>}<p className="text-sm text-text-secondary">확인한 현재 버전은 나만 보기로 초기화됩니다. 확인하지 않은 문서는 연결은 유지되지만 범위가 회수되어 다시 지정할 때까지 모델에 제공되지 않습니다.</p><label className={vaultLabel}>확인할 문서 검색<input className="rounded-md border border-border bg-bg px-3 py-2 text-sm text-text" value={rebindQuery} onChange={event => { setRebindQuery(event.target.value); setRebindPage(0); }} /></label><div className="flex items-center gap-2 text-xs text-text-secondary"><button className={vaultButton} disabled={busy || confirmableIds.length === 0} onClick={() => setConfirmed(current => Array.from(new Set([...current, ...confirmableIds])))} type="button">검색 결과 모두 확인</button><button className={vaultButton} disabled={busy || confirmed.length === 0} onClick={() => setConfirmed([])} type="button">모두 해제</button><span>확인 {confirmed.length} / {rebindDocs.filter(item => item.current_revision_id).length}</span></div>{visibleCandidates.flatMap(item => item.current_revision_id ? [[item, item.current_revision_id] as const] : []).map(([item, revisionId]) => <label className="grid gap-1 text-sm text-text-secondary" key={revisionId}><span className="flex items-center gap-2"><input checked={confirmed.includes(revisionId)} disabled={busy} onChange={() => setConfirmed(current => current.includes(revisionId) ? current.filter(id => id !== revisionId) : [...current, revisionId])} type="checkbox" />{item.title}</span><span className="break-all text-xs">버전: {revisionId} · 해시: {item.current_revision_hash ?? "없음"} · 범위: {item.current_scope === "private-data" ? "나만 보기" : item.current_scope === "common" ? "모든 프로젝트" : "이 프로젝트"}</span></label>)}<div className="flex gap-2"><button className={vaultButton} disabled={rebindPage === 0} onClick={() => setRebindPage(page => page - 1)} type="button">이전</button><button className={vaultButton} disabled={(rebindPage + 1) * 100 >= candidates.length} onClick={() => setRebindPage(page => page + 1)} type="button">다음</button></div><div className="flex gap-2"><button className={vaultButton} disabled={busy || !rebindPath} onClick={() => void mutate(async () => { await vaultRebind(rebind.id, rebindPath, confirmed, host); setRebind(null); setRebindPath(""); })} type="button">새 위치로 다시 연결</button><button className={vaultButton} disabled={busy} onClick={() => { rebindRequest.current++; setRebind(null); }} type="button">취소</button></div></section>}
    {status && <section className="space-y-2 border-t border-border pt-3"><h3 className="font-medium">복구</h3>{status.index_rebuild_needed && <p className="text-sm text-text-secondary">색인 재구축이 필요합니다. 자료함에서 디렉터리 스캔을 실행하세요.</p>}<p className="text-sm text-text-secondary">미완료 작업 충돌: {status.operation_conflicts.length}건</p>{status.operation_conflicts.map(item => <p className="break-all text-xs text-text-secondary" key={item.id}>{item.relative_path}</p>)}<button className={vaultButton} disabled={busy} onClick={() => void mutate(async () => { const report = await vaultRecoverOperations(host); setRecovery(`복구 ${report.recovered}건 · 충돌 ${report.conflicts}건`); })} type="button">미완료 작업 확인</button>{recovery && <p role="status" className="text-sm text-text-secondary">{recovery}</p>}</section>}
    {projectBinding && <section className="space-y-2 border-t border-border pt-3"><h3 className="font-medium">프로젝트 위치 변경</h3><p className="break-all text-xs text-text-secondary">{projectBinding.canonical_repo_root}</p><button className={vaultButton} disabled={busy} onClick={() => void open({ directory: true, multiple: false }).then(path => { if (typeof path === "string") setProjectPath(path); }).catch(reason => setError(String(reason)))} type="button">새 프로젝트 위치 선택</button>{projectPath && <><p className="break-all text-sm text-text-secondary">새 위치: {projectPath}</p><button className={vaultButton} disabled={busy} onClick={() => void mutate(async () => { await vaultRebindProject(projectBinding.id, projectPath, host); setProjectPath(""); })} type="button">프로젝트 다시 연결</button></>}</section>}
  </section>;
}
