import assert from 'node:assert/strict';
import { mkdir, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { chromium } from 'playwright';
import { createServer } from 'vite';
import react from '@vitejs/plugin-react';

const fixture = path.resolve('.praxis/verification/wikiskill-smoke/ui-fixture');
await mkdir(fixture, { recursive: true });
await writeFile(path.join(fixture, 'index.html'), '<div id="root"></div><script type="module" src="./main.tsx"></script>');
await writeFile(path.join(fixture, 'main.tsx'), `
import React from 'react';
import { createRoot } from 'react-dom/client';
import { WikiView } from '/src/components/WikiView';
import '/src/index.css';
document.documentElement.classList.add('dark');
createRoot(document.getElementById('root')).render(<main className="bg-bg text-text flex flex-col" style={{height:'100dvh',width:'100%'}}><WikiView repo="/workspace/alpha" canAttach dark onAttach={async()=>{}} /></main>);
`);
await writeFile(path.join(fixture, 'api.ts'), `
import { overview, proposal, evidence } from '/src/components/wikiskill/__fixtures__/wiki';
let data=overview();
const copy=()=>structuredClone(data);
export const wikiSkillProjects=async()=>[data.project];
export const wikiSkillOverview=async()=>copy();
export const wikiSkillSnapshot=async(_project,id)=>({id,task_id:1,hash:'a'.repeat(64),body:'저장한 실행 기록입니다. 원본을 수정해도 이 사본은 유지됩니다.',truncated:true,created_at:1788600000});
export const wikiSkillRevision=async()=>structuredClone(data.patterns[0]);
export const wikiSkillAnalyze=async(_project,ids)=>{if(!ids.length||ids.length>5)throw Error('invalid selection');return copy();};
export const wikiSkillPropose=async(_project,ids,name)=>{if(ids[0]!==1)throw Error('wrong provenance');data.proposals=[{...proposal,name}];return copy();};
export const wikiSkillCreateTrial=async(_project,id,goal)=>{const trial={id:20,proposal_id:id,goal,baseline_instruction:'EXACT BASELINE PROMPT',candidate_instruction:'EXACT CANDIDATE PROMPT',created_at:1788600021};data.trials=[trial];return trial;};
export const wikiSkillEvaluate=async(_project,trial,b,c)=>{if(b!==2||c!==3)throw Error('wrong pair');const result={id:30,trial_id:trial,baseline:{...evidence(b,4),instruction:'EXACT BASELINE PROMPT'},candidate:{...evidence(c,5),instruction:'EXACT CANDIDATE PROMPT'},eligible:true,reason:null,baseline_rate:.8,candidate_rate:1,created_at:1788600050};data.evaluations=[result];return result;};
export const wikiSkillDecide=async(_project,id,decision)=>{data.proposals=[{...data.proposals[0],status:decision==='accept'?'accepted':decision==='rollback'?'rolled_back':'rejected',decided_at:1788600060}];data.active=decision==='accept'?[{version_id:40,proposal_id:id,name:data.proposals[0].name,body:data.proposals[0].candidate_body,accepted_at:1788600060}]:[];return copy();};
`);
await writeFile(path.join(fixture, 'legacy.ts'), `export const wikiSpaces=async()=>[]; export const wikiDocuments=async()=>({documents:[],truncated:false});export const wikiReadDocument=async()=>{throw Error('no document');};export const wikiSync=async()=>({complete:true,warnings:[],indexed:0,skipped:0,deleted:0,edges:0});export const wikiConnect=async()=>{throw Error('fixture only');};`);
let server, browser;
const screenshots = [];
try {
  server = await createServer({ configFile: false, plugins: [{ name: 'wikiskill-fixture', enforce: 'pre', resolveId(source) {
    if (source.endsWith('/wikiskill-ipc')) return path.join(fixture, 'api.ts');
    if (source.endsWith('/wiki-ipc')) return path.join(fixture, 'legacy.ts');
  } }, react()], server: { host: '127.0.0.1', port: 0 }, logLevel: 'error' });
  await server.listen();
  browser = await chromium.launch({ headless: true, channel: process.env.PRAXIS_SMOKE_BROWSER || 'chrome' });
  const page = await browser.newPage({ viewport: { width: 1360, height: 940 } });
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.addInitScript(() => { window.__copies=[];Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async text=>{window.__copies.push(text);}}}); });
  await page.goto(server.resolvedUrls.local[0] + path.relative(process.cwd(), fixture) + '/index.html');
  await page.getByRole('button', { name: '기존 Wiki', exact: true }).click();
  await page.getByText('변경 범위에 맞춘 검증', { exact: true }).waitFor();
  const shot = async name => { const file=`/tmp/praxis-wikiskill-${name}.png`;await page.screenshot({path:file});screenshots.push(file); };
  await shot('dark');
  await page.evaluate(() => document.documentElement.classList.remove('dark')); await shot('light');
  await page.setViewportSize({width:390,height:844});
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await shot('narrow');
  await page.setViewportSize({width:1360,height:940});
  await page.evaluate(() => document.documentElement.classList.add('dark'));
  await page.getByRole('button', { name:'실행 근거 #1',exact:true }).click();
  await page.getByText('저장한 실행 기록입니다.', {exact:false}).waitFor();
  await page.getByRole('button',{name:'닫기',exact:true}).click();
  await page.getByRole('tab',{name:'실행 기록',exact:true}).click();
  await page.getByLabel('실행 선택 1',{exact:true}).check();
  await page.getByRole('button',{name:'선택한 실행 분석',exact:true}).click();
  await page.getByLabel('지식 선택 변경 범위에 맞춘 검증',{exact:true}).check();
  await page.getByLabel('스킬 이름',{exact:true}).fill('review-checklist');
  await page.getByRole('button',{name:'스킬 초안 만들기',exact:true}).click();
  await page.getByRole('heading',{name:'review-checklist',exact:true}).waitFor();
  assert(await page.getByRole('button',{name:'스킬 채택',exact:true}).isDisabled());
  await page.getByLabel('비교할 목표',{exact:true}).fill('별도 회귀 사례에서 변경 동작을 검증한다.');
  await page.getByRole('button',{name:'비교 프롬프트 만들기',exact:true}).click();
  await page.getByRole('button',{name:'기준 프롬프트 복사',exact:true}).click();
  assert.equal(await page.evaluate(()=>window.__copies.at(-1)),'EXACT BASELINE PROMPT');
  const choose = async(label,id) => { const summary=page.getByLabel(label,{exact:true});await summary.click();await summary.locator('..').getByRole('button',{name:new RegExp('^#'+id+' ·')}).click(); };
  await choose('기준 실행 20',2);await choose('후보 실행 20',3);
  await page.getByRole('button',{name:'실행 결과 비교',exact:true}).click();
  await page.getByText('이 비교에서 개선됨',{exact:true}).waitFor();
  await shot('comparison');
  await page.getByRole('button',{name:'스킬 채택',exact:true}).click();
  await page.getByRole('tab',{name:'지식',exact:true}).click();
  await page.getByRole('button',{name:'지침 복사',exact:true}).click();
  assert((await page.evaluate(()=>window.__copies.at(-1))).includes('변경 범위'));
  await page.getByRole('button',{name:'되돌리기',exact:true}).click();
  await page.getByText('채택한 스킬이 없습니다.',{exact:true}).waitFor();
  await page.getByRole('tab',{name:'문서 자료',exact:true}).click();
  await page.getByRole('button',{name:/폴더 연결/}).waitFor();
  assert.deepEqual(errors,[]);
  console.log('PASS: actual Wiki shell + components, knowledge/source, analysis, proposal, prompts, evaluation, accept/copy/rollback, legacy docs; no page errors. Synthetic IPC only.');
  console.log(screenshots.join('\n'));
} finally {
  await browser?.close(); await server?.close(); await rm(fixture,{recursive:true,force:true});
}
